[package]
name = "nifti-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nifti = "0.14.0"
ndarray = "0.15.6"
image = "0.24.4"